# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/intelight/PYNQ-Z1_C.xdc

# Block Designs: bd/testbench/testbench.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testbench || ORIG_REF_NAME==testbench} -quiet] -quiet

# IP: bd/testbench/ip/testbench_QA_0_0/testbench_QA_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testbench_QA_0_0 || ORIG_REF_NAME==testbench_QA_0_0} -quiet] -quiet

# IP: bd/testbench/ip/testbench_PG_0_0/testbench_PG_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testbench_PG_0_0 || ORIG_REF_NAME==testbench_PG_0_0} -quiet] -quiet

# IP: bd/testbench/ip/testbench_SD_0_0/testbench_SD_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testbench_SD_0_0 || ORIG_REF_NAME==testbench_SD_0_0} -quiet] -quiet

# IP: bd/testbench/ip/testbench_RD_0_0/testbench_RD_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testbench_RD_0_0 || ORIG_REF_NAME==testbench_RD_0_0} -quiet] -quiet

# IP: bd/testbench/ip/testbench_cnst_0_4bit_0/testbench_cnst_0_4bit_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testbench_cnst_0_4bit_0 || ORIG_REF_NAME==testbench_cnst_0_4bit_0} -quiet] -quiet

# IP: bd/testbench/ip/testbench_Action_RAM_2_0/testbench_Action_RAM_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testbench_Action_RAM_2_0 || ORIG_REF_NAME==testbench_Action_RAM_2_0} -quiet] -quiet

# IP: bd/testbench/ip/testbench_PL_RAM_2_0/testbench_PL_RAM_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testbench_PL_RAM_2_0 || ORIG_REF_NAME==testbench_PL_RAM_2_0} -quiet] -quiet

# IP: bd/testbench/ip/testbench_Action_RAM_1_0/testbench_Action_RAM_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testbench_Action_RAM_1_0 || ORIG_REF_NAME==testbench_Action_RAM_1_0} -quiet] -quiet

# IP: bd/testbench/ip/testbench_PL_RAM_1_0/testbench_PL_RAM_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testbench_PL_RAM_1_0 || ORIG_REF_NAME==testbench_PL_RAM_1_0} -quiet] -quiet

# IP: bd/testbench/ip/testbench_Action_RAM_3_0/testbench_Action_RAM_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testbench_Action_RAM_3_0 || ORIG_REF_NAME==testbench_Action_RAM_3_0} -quiet] -quiet

# IP: bd/testbench/ip/testbench_PL_RAM_3_0/testbench_PL_RAM_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testbench_PL_RAM_3_0 || ORIG_REF_NAME==testbench_PL_RAM_3_0} -quiet] -quiet

# IP: bd/testbench/ip/testbench_PL_RAM_0_0/testbench_PL_RAM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testbench_PL_RAM_0_0 || ORIG_REF_NAME==testbench_PL_RAM_0_0} -quiet] -quiet

# IP: bd/testbench/ip/testbench_Action_RAM_0_0/testbench_Action_RAM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testbench_Action_RAM_0_0 || ORIG_REF_NAME==testbench_Action_RAM_0_0} -quiet] -quiet

# IP: bd/testbench/ip/testbench_CU_0_0/testbench_CU_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testbench_CU_0_0 || ORIG_REF_NAME==testbench_CU_0_0} -quiet] -quiet

# IP: bd/testbench/ip/testbench_bram_input_interface_0_0/testbench_bram_input_interface_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testbench_bram_input_interface_0_0 || ORIG_REF_NAME==testbench_bram_input_interface_0_0} -quiet] -quiet

# IP: bd/testbench/ip/testbench_bram_output_interface_0_0/testbench_bram_output_interface_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testbench_bram_output_interface_0_0 || ORIG_REF_NAME==testbench_bram_output_interface_0_0} -quiet] -quiet

# XDC: d:/intelight/intelight/intelight.gen/sources_1/bd/testbench/testbench_ooc.xdc
