# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/intelight/PYNQ-Z1_C.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_SD_0_0/system_SD_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_SD_0_0 || ORIG_REF_NAME==system_SD_0_0} -quiet] -quiet

# IP: bd/system/ip/system_RD_0_0/system_RD_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_RD_0_0 || ORIG_REF_NAME==system_RD_0_0} -quiet] -quiet

# IP: bd/system/ip/system_PG_0_0/system_PG_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_PG_0_0 || ORIG_REF_NAME==system_PG_0_0} -quiet] -quiet

# IP: bd/system/ip/system_QA_0_0/system_QA_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_QA_0_0 || ORIG_REF_NAME==system_QA_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_50M_1/system_rst_ps7_0_50M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_50M_1 || ORIG_REF_NAME==system_rst_ps7_0_50M_1} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_1/system_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_1 || ORIG_REF_NAME==system_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/system/ip/system_intelight_mem_0_0/system_intelight_mem_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_intelight_mem_0_0 || ORIG_REF_NAME==system_intelight_mem_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_intc_0_0/system_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_intc_0_0 || ORIG_REF_NAME==system_axi_intc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_bram_interface_0_0/system_bram_interface_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_bram_interface_0_0 || ORIG_REF_NAME==system_bram_interface_0_0} -quiet] -quiet

# IP: bd/system/ip/system_cnst_0_4bit_0/system_cnst_0_4bit_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cnst_0_4bit_0 || ORIG_REF_NAME==system_cnst_0_4bit_0} -quiet] -quiet

# IP: bd/system/ip/system_cnst_1_1bit_0/system_cnst_1_1bit_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cnst_1_1bit_0 || ORIG_REF_NAME==system_cnst_1_1bit_0} -quiet] -quiet

# IP: bd/system/ip/system_Action_RAM_2_0/system_Action_RAM_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Action_RAM_2_0 || ORIG_REF_NAME==system_Action_RAM_2_0} -quiet] -quiet

# IP: bd/system/ip/system_PL_RAM_1_0/system_PL_RAM_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_PL_RAM_1_0 || ORIG_REF_NAME==system_PL_RAM_1_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_bram_ctrl_0_5/system_axi_bram_ctrl_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_bram_ctrl_0_5 || ORIG_REF_NAME==system_axi_bram_ctrl_0_5} -quiet] -quiet

# IP: bd/system/ip/system_Action_RAM_1_0/system_Action_RAM_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Action_RAM_1_0 || ORIG_REF_NAME==system_Action_RAM_1_0} -quiet] -quiet

# IP: bd/system/ip/system_blk_mem_gen_0_0/system_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_blk_mem_gen_0_0 || ORIG_REF_NAME==system_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_bram_ctrl_0_3/system_axi_bram_ctrl_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_bram_ctrl_0_3 || ORIG_REF_NAME==system_axi_bram_ctrl_0_3} -quiet] -quiet

# IP: bd/system/ip/system_Action_RAM_3_0/system_Action_RAM_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Action_RAM_3_0 || ORIG_REF_NAME==system_Action_RAM_3_0} -quiet] -quiet

# IP: bd/system/ip/system_PL_RAM_2_0/system_PL_RAM_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_PL_RAM_2_0 || ORIG_REF_NAME==system_PL_RAM_2_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_bram_ctrl_0_2/system_axi_bram_ctrl_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_bram_ctrl_0_2 || ORIG_REF_NAME==system_axi_bram_ctrl_0_2} -quiet] -quiet

# IP: bd/system/ip/system_PL_RAM_3_0/system_PL_RAM_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_PL_RAM_3_0 || ORIG_REF_NAME==system_PL_RAM_3_0} -quiet] -quiet

# IP: bd/system/ip/system_Action_RAM_0_0/system_Action_RAM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Action_RAM_0_0 || ORIG_REF_NAME==system_Action_RAM_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_bram_ctrl_0_4/system_axi_bram_ctrl_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_bram_ctrl_0_4 || ORIG_REF_NAME==system_axi_bram_ctrl_0_4} -quiet] -quiet

# IP: bd/system/ip/system_CU_0_0/system_CU_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_CU_0_0 || ORIG_REF_NAME==system_CU_0_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_2/system_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_2 || ORIG_REF_NAME==system_auto_pc_2} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_1 || ORIG_REF_NAME==system_auto_pc_1} -quiet] -quiet

# XDC: d:/intelight/intelight/intelight.gen/sources_1/bd/system/system_ooc.xdc
