# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/intelight/intelight/intelight.srcs/sources_1/bd/system/ip/system_axi_bram_ctrl_0_5/system_axi_bram_ctrl_0_5.xci
# IP: The module: 'system_axi_bram_ctrl_0_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/intelight/intelight/intelight.gen/sources_1/bd/system/ip/system_axi_bram_ctrl_0_5/system_axi_bram_ctrl_0_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_bram_ctrl_0_5'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/intelight/intelight/intelight.srcs/sources_1/bd/system/ip/system_axi_bram_ctrl_0_5/system_axi_bram_ctrl_0_5.xci
# IP: The module: 'system_axi_bram_ctrl_0_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/intelight/intelight/intelight.gen/sources_1/bd/system/ip/system_axi_bram_ctrl_0_5/system_axi_bram_ctrl_0_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_bram_ctrl_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
