@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Mar 24 02:41:37 +0700 2022
REM SW Build 3247384 on Thu Jun 10 19:36:33 MDT 2021
REM
REM IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim testbench_wrapper_tb_time_synth -key {Post-Synthesis:sim_1:Timing:testbench_wrapper_tb} -tclbatch testbench_wrapper_tb.tcl -protoinst "protoinst_files/testbench.protoinst" -protoinst "protoinst_files/system.protoinst" -protoinst "protoinst_files/memory.protoinst" -view D:/intelight/intelight/system_wrapper_tb_behav.wcfg -log simulate.log"
call xsim  testbench_wrapper_tb_time_synth -key {Post-Synthesis:sim_1:Timing:testbench_wrapper_tb} -tclbatch testbench_wrapper_tb.tcl -protoinst "protoinst_files/testbench.protoinst" -protoinst "protoinst_files/system.protoinst" -protoinst "protoinst_files/memory.protoinst" -view D:/intelight/intelight/system_wrapper_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
