# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Dismas/ITB/SemesterVIII/TA2/intelight/intelight.srcs/sources_1/bd/system/ip/system_Action_RAM_3_0/system_Action_RAM_3_0.xci
# IP: The module: 'system_Action_RAM_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Dismas/ITB/SemesterVIII/TA2/intelight/intelight.gen/sources_1/bd/system/ip/system_Action_RAM_3_0/system_Action_RAM_3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_Action_RAM_3_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Dismas/ITB/SemesterVIII/TA2/intelight/intelight.srcs/sources_1/bd/system/ip/system_Action_RAM_3_0/system_Action_RAM_3_0.xci
# IP: The module: 'system_Action_RAM_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Dismas/ITB/SemesterVIII/TA2/intelight/intelight.gen/sources_1/bd/system/ip/system_Action_RAM_3_0/system_Action_RAM_3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_Action_RAM_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
